export const GET_ALL_VIDEOGAMES = 'GET_ALL_VIDEOGAMES';
export const GET_VIDEOGAME_BY_NAME = 'GET_VIDEGAME_BY_NAME';
export const ORDER_BY_GENRE = 'ORDER_BY_GENRE';
export const ORDER_ALPHABETICALY = 'ORDER_ALPHABETICALY'
